- hosts: web
  become_user: root
  become: yes
  gather_facts: yes
  tasks:
    - name: create directory
      file: 
        path: /tmp/data
        state: directory

    - name: copy file
      content: /tmp/data/hellow.html
