- hosts: web
  become_user: root
  become: yes
  gather_facts: yes
  tasks:
    - name: create directory
      file: 
        path: /tmp/data
        state: directory

    - name: copy file
      copy:
        content: "this is my testing play, My name is Ganesh"
        dest: /tmp/data/hellow.html
